### ISSUE TITLE
Update from 0.86.1 to 0.87.0 breaks OIDC Logon

### ISSUE THREAD

**Issue by rattencreep** [outline/outline#10061]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### This is not related to configuring Outline

- [x] The issue is not related to self-hosting config

### Current Behavior

After the update from 0.86.1 to 0.87.0 it is no longer possible to logon with OIDC (authentik):
<img width="327" height="99" alt="Image" src="https://github.com/user-attachments/assets/e7d48334-c0cd-46ba-96f2-047663503a5a" />
The logs show:
`"request to https://sub.domain.tld/application/o/userinfo/ failed, reason: DNS lookup 10.10.XX.XX(family:4, host:sub.domain.tld) is not allowed. Because, It is private IP address."`

### Expected Behavior

Being able to logon as usual.

### Steps To Reproduce

Update from 0.86.1 to 0.87.0

### Environment

```markdown
- Outline: Outline 0.87.0
- Browser: Firefox, Brave
- IDP: authentic (OIDC)
```

### Anything else?

Full error log:
`{"error":"request to https://sub.domain.tld/application/o/userinfo/ failed, reason: DNS lookup 10.10.XX.XX(family:4, host:sub.domain.tld) is not allowed. Because, It is private IP address.","level":"error","message":"Error processing task in ValidateSSOAccessTask","stack":"BadRequestError: request to https://sub.domain.tld/application/o/userinfo/ failed, reason: DNS lookup 10.10.XX.XX(family:4, host:sub.domain.tld) is not allowed. Because, It is private IP address.\n    at InvalidRequestError (/opt/outline/build/server/errors.js:107:34)\n    at OIDCClient.userInfo (/opt/outline/build/server/utils/osub.js:36:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:76:9)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:34:18\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:32:24\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.&lt;anonymous&gt; (/opt/outline/build/server/services/worker.js:129:14)"}`

**Comment by tommoor** [comment]
Fixed in `v0.87.2`

**Comment by rattencreep** [comment]
I am sorry to say, it is not quite fixed. This is the log of 0.87.2:
`{"error":"request to https://sub.domain.tld/application/o/userinfo/ failed, reason: DNS lookup 10.10.XX.XX(family:4, host:sub.domain.tld) is not allowed. Because, It is private IP address.","level":"error","message":"Error during subentication","stack":"FetchError: request to https://sub.domain.tld/application/o/userinfo/ failed, reason: DNS lookup 10.10.XX.XX(family:4, host:sub.domain.tld) is not allowed. Because, It is private IP address.\n    at ClientRequest.&lt;anonymous&gt; (/opt/outline/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at emitErrorEvent (node:_http_client:105:11)\n    at TLSSocket.socketErrorListener (node:_http_client:518:5)\n    at TLSSocket.emit (node:events:519:28)\n    at TLSSocket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}`

and this error is new:
`{"error":"invalid json response body at https://sub.domain.tld/application/o/userinfo/ reason: Unexpected end of JSON input","level":"error","message":"Error processing task in ValidateSSOAccessTask","stack":"BadRequestError: invalid json response body at https://sub.domain.tld/application/o/userinfo/ reason: Unexpected end of JSON input\n    at InvalidRequestError (/opt/outline/build/server/errors.js:107:34)\n    at OIDCClient.userInfo (/opt/outline/build/server/utils/osub.js:37:47)\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)\n    at async UserAuthentication.validateAccess (/opt/outline/build/server/models/UserAuthentication.js:76:9)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:34:18\n    at async Promise.all (index 0)\n    at async /opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:32:24\n    at async /opt/outline/node_modules/sequelize/lib/sequelize.js:507:18\n    at async ValidateSSOAccessTask.perform (/opt/outline/build/server/queues/tasks/ValidateSSOAccessTask.js:18:5)\n    at async Queue.&lt;anonymous&gt; (/opt/outline/build/server/services/worker.js:129:14)"}`

**Comment by tommoor** [comment]
But you can login now?

**Comment by rattencreep** [comment]
No, I can't. 

<img width="327" height="99" alt="Image" src="https://github.com/user-attachments/assets/eceae8ab-b49f-4e16-a9e6-384ae64d7e23" />

**Comment by tommoor** [comment]
Are you using any sort of proxy?

**Comment by steccas** [comment]
Hi all, its still broken here. I'm using authelia, they are in the same docker network. The log says: ```sd_outline  | {"error":"request to http://authelia:9091/api/oidc/userinfo failed, reason: DNS lookup 172.17.13.2(family:4, host:authelia) is not allowed. Because, It is private IP address.","level":"error","message":"Error during authentication","stack":"FetchError: request to http://authelia:9091/api/oidc/userinfo failed, reason: DNS lookup 172.17.13.2(family:4, host:authelia) is not allowed. Because, It is private IP address.\n    at ClientRequest.<anonymous> (/opt/outline/node_modules/node-fetch/lib/index.js:1501:11)\n    at ClientRequest.emit (node:events:519:28)\n    at ClientRequest.emit (node:domain:489:12)\n    at emitErrorEvent (node:_http_client:105:11)\n    at Socket.socketErrorListener (node:_http_client:518:5)\n    at Socket.emit (node:events:519:28)\n    at Socket.emit (node:domain:489:12)\n    at emitErrorNT (node:internal/streams/destroy:170:8)\n    at emitErrorCloseNT (node:internal/streams/destroy:129:3)\n    at process.processTicksAndRejections (node:internal/process/task_queues:90:21)"}```

**Comment by tommoor** [comment]
Urgh, this is very frustrating :(

**Comment by rattencreep** [comment]
I do use a proxy - traefik.

**Comment by tommoor** [comment]
Ok, building one more [fix as a prerelease now](https://github.com/outline/outline/actions/runs/17376669081) (`v0.87.3-0`) – will get a confirmation from a few folks in this thread before doing another patch release proper

**Comment by edvgui** [comment]
`docker.io/outlinewiki/outline:0.87.3-0` works for me.  Thanks @tommoor !

**Comment by rattencreep** [comment]
Works for me as well. Logs are clean. Thank you!

**Comment by steccas** [comment]
It works for me too! Thank you

**Comment by tommoor** [comment]
Published as [v0.87.3](https://github.com/outline/outline/releases/tag/v0.87.3) now – If it's any solace this change was part of increased security hardening.
