### ISSUE TITLE
docx import fails on Chrome and Edge

### ISSUE THREAD

**Issue by mtlynch** [outline/outline#2104]
#1551 added support for docx files, but it only seems to work on Firefox. On Chrome and Edge (latest versions on Win10), it fails with `File type application/octet-stream not supported`.

**To Reproduce**
1. From a collections page, click `Import Document`
2. From the file picker dialog, change file type to `All files (*.*)`
3. Select a `.docx` file

**Expected behavior**

Outline shows .docx files in the file dialog and allows importing of docx files.

**Actual behavior**

docx upload fails with `File type application/octet-stream not supported`

**More details**

The bug is on [this line of documentImporter.js](https://github.com/outline/outline/blob/49ffcda8e051abf9429a74782f3ce6af417253ec/server/commands/documentImporter.js#L49). It assumes that all browsers upload `.docx` files with mimetype `application/vnd.openxmlformats-officedocument.wordprocessingml.document`. Firefox does use that mimetype, but both Chrome and Edge upload `.docx` files as `application/octet-stream`.

**Screenshots**

![image](https://user-images.githubusercontent.com/7783288/116821107-89081200-ab46-11eb-83e4-9133f6e63102.png)

![image](https://user-images.githubusercontent.com/7783288/116813117-36b3fa80-ab20-11eb-8ae2-57d016164750.png)

**Outline (please complete the following information):**
- Install: getoutline.com
- Version: n/a

**Desktop (please complete the following information):**
 - OS: Win10 x64
 - Browser Chrome
 - Version 90

**Comment by iamsaumya** [comment]
I find this issue similar to the conversation [here](https://groups.google.com/g/drchrono-api/c/-jk7zGz6pBU). 

Is there anything unusual in the way you created this `.docx` file?

**Comment by mtlynch** [comment]
Nope, just exported straight from Google Docs. Notion imports it fine.

**Comment by iamsaumya** [comment]
I see. I'm not sure how to reproduce this on my machine 🤔

**Comment by mtlynch** [comment]
What OS and browser are you trying to reproduce on? Are you seeing `.docx` in the list of supported file extensions in the file picker dialog?

**Comment by iamsaumya** [comment]
I am using `Ubuntu 20.04` and Brave Browser. Yes, I did change the file type to "All files" and I was able to import `.docx`.

**Comment by iamsaumya** [comment]
Are there any helpful errors in the network panel or console?

**Comment by mtlynch** [comment]
> Yes, I did change the file type to "All files" and I was able to import .docx.

Do you agree that this part is a bug? If docx is supported, it should appear in the list of supported extensions in the file dialog picker.

>I am using Ubuntu 20.04 and Brave Browser.

Can you try to reproduce using Chrome?

**Comment by iamsaumya** [comment]
>  If docx is supported, it should appear in the list of supported extensions

For me, it is appearing in the "All supported types" file type.

**Comment by mtlynch** [comment]
>>If docx is supported, it should appear in the list of supported extensions

>For me, it is appearing in the "All supported types" file type.

I'm a bit confused. Earlier you said you had to change the file type to "All files" in order to see .docx. Now, it sounds like you're saying that it appeared under the default list.

This is what I'm seeing:

![image](https://user-images.githubusercontent.com/7783288/116821190-df755080-ab46-11eb-9b73-189018574069.png)

Note that .docx is missing from the list.

I've provided the repro steps. If you're having trouble understanding them, I'm happy to clarify, but I'm not that enthusiastic to keep engaging when it doesn't feel like you're doing your due diligence in handling this bug report.

If you can't repro in a different OS and browser, please try repro'ing in the browser and OS where I reported that the problem occurs.

**Comment by tommoor** [comment]
@mtlynch the report is clear, thanks for providing all the details you have so far. Seems likely to be a Windows difference, I'll try and repro there.

**Comment by tommoor** [comment]
@mtlynch fix deployed to production, thanks again for the report

**Comment by mtlynch** [comment]
@tommoor Thanks for the fix! Fix confirmed on my end.

Not sure if you're aware, but `.docx` still doesn't show up in the list of supported extensions:

![image](https://user-images.githubusercontent.com/7783288/117381289-be479380-aea9-11eb-8aca-851f1f43c075.png)

**Comment by tommoor** [comment]
Do you actually have Word installed on your machine? If it's not installed then it would make sense that it doesn't know how to map the mimetype to an extension.

**Comment by mtlynch** [comment]
I don't have Word installed. Is it expected that it only works for users with Word installed?

Not sure if it's relevant, but Win10 can open .docx files even if Office has never been installed. WordPad ships with Windows and has limited support for docx.

Would it be possible to set the supported file types explicitly to the extensions that Outline supports rather than inferring from the client system? It seems like the current implementation is including unsupported files (`.com`, `.exe`, `.bin`) and excluding supported ones (`.docx`).

My scenario is importing from Google Docs. A .docx file seems like the most accurate way to go from Docs -> Outline, but maybe this is an unusual path.

**Comment by tommoor** [comment]
> Would it be possible to set the supported file types explicitly to the extensions that Outline supports

Yes, we should add the explicit extensions in the frontend it seems like mimetypes just aren't working as a good solution here unfortunately.  Filed as a follow up: https://github.com/outline/outline/issues/2123
