### ISSUE TITLE
Some document actions only work in document view (firefox)

### ISSUE THREAD

**Issue by ledge74** [outline/outline#2140]
Document actions (delete, archive, ...) only work in the document view. If you try to do these actions from any other page it doesn't do anything. I've also tested on Safari and it works like it is supposed to.

**To Reproduce**
1. Go to drafts (or any other view that is not the document view)
2. Click on '....' on a document
3. Click on Delete
4. Nothing happens

**Expected behavior**
Delete window should appear

**Screenshots**
![ezgif-2-f573a6850f02](https://user-images.githubusercontent.com/6603944/118360865-5cfa8100-b589-11eb-8430-31e3792a6c8d.gif)

**Outline (please complete the following information):**
- Install: selfhosted
- Version: 0.55.0

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser firefox 88.0.1 (64 bits)

**Comment by tommoor** [comment]
Thanks for filing – this was fixed here https://github.com/outline/outline/pull/2060 and will be included in the next release.

**Comment by ledge74** [comment]
@tommoor i've tried the current development version with #2060 merged in the codebase and this issue is still happening.
