### ISSUE TITLE
Inline code is hard to use

### ISSUE THREAD

**Issue by muuvmuuv** [outline/outline#3210]
Typing inline code is pretty annoying, it always appends a ` or when attempting to remove it with <kbd>SHIFT + ARROW LEFT</kbd> it ends up that you cannot longer type normal text afterwards.

**To Reproduce**
1. Type `
2. Write some text
3. Type `
4. Press <kbd>SPACE</kbd>

**Expected behavior**

After pressing space, the ` should disappear and normal text should continue.

**Screenshots**

<img width="144" alt="Bildschirmfoto 2022-03-08 um 07 46 18" src="https://user-images.githubusercontent.com/11534760/157182183-38d2b03c-4d92-4c62-ad52-33282099b3d8.png">

**Outline (please complete the following information):**
- Install: self hosted
- Version: v0.61.1

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Brave PWA
 - Version always latest

**Comment by tommoor** [comment]
Unable to reproduce in Brave here, try the latest version of Outline.

https://user-images.githubusercontent.com/380914/157183090-a2fb767a-ac40-444e-8539-6475d0540d4e.mov

**Comment by Limezy** [comment]
Able to reproduce here.
@tommoor please try using the "US International" keyboard layout to reproduce

**Comment by muuvmuuv** [comment]
fyi: I use a German keyboard

**Comment by tommoor** [comment]
The code in question is here, it will probably have to be fixed by someone that's able to reproduce:
https://github.com/outline/outline/blob/main/shared%2Feditor%2Fmarks%2FCode.ts#L49

**Comment by muuvmuuv** [comment]
I don't have the time to work on that but would like to keep that open as an improvement.

**Comment by tommoor** [comment]
Unless there are reproduction steps there is no possibility of fixing. The keyboard layout should not make a difference as we do not check keycodes – we check the actual character typed. If someone can provide a video of the bug it may be useful.

**Comment by Limezy** [comment]
Hi @tommoor thanks for your time spent on that issue.

I really believe it's an issue linked to the keyboard layout. US International layout has a kind of "intermediate" keystroke where you'll have typed an accent and it's waiting for the letter to be typed behind. 

Below is a video comparing Typora (working) and Outline (not working).
I hope it's usefull !


https://user-images.githubusercontent.com/24638389/163516211-5a757331-b88a-4f82-b9ca-1e648b648eb3.mov

**Comment by Limezy** [comment]
(Maybe worth reading, the same troubles have been solved by Flarum team a few months ago : https://discuss.flarum.org/d/26027-extend-markdown-to-disable-inline-key-binding)

**Comment by muuvmuuv** [comment]
The issue still persists in 0.65.2. What else on information is needed?

**Comment by tommoor** [comment]
I think the information is clear but as stated before this bug just does not reproduce on my machine – it also doesn't make any sense to me based on the way that the logic is constructed as we check the character not keycodes, so it's going to take someone that can reproduce it to fix it…

**Comment by Limezy** [comment]
Well, it takes as little as using the "US international" keyboard mapping to reproduce. It takes 30s to change on MacOS, which I believe you are using

**Comment by muuvmuuv** [comment]
![Bildschirmaufnahme 2022-10-24 um 08 29 08](https://user-images.githubusercontent.com/11534760/197461800-2200ff40-932e-4380-aa9b-dc9d8d26c479.gif)

My keyboard settings via `defaults read ~/Library/Preferences/com.apple.HIToolbox.plist`: 

```
{
    AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.German";
    AppleEnabledInputSources =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        },
                {
            "Bundle ID" = "com.apple.CharacterPaletteIM";
            InputSourceKind = "Non Keyboard Input Method";
        },
                {
            "Bundle ID" = "com.apple.PressAndHold";
            InputSourceKind = "Non Keyboard Input Method";
        }
    );
    AppleFnUsageType = 2;
    AppleInputSourceHistory =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        }
    );
    AppleSelectedInputSources =     (
                {
            "Bundle ID" = "com.apple.PressAndHold";
            InputSourceKind = "Non Keyboard Input Method";
        },
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        }
    );
}
```

**Comment by herzkerl** [comment]
@muuvmuuv Thanks for the GIF. @tommoor you'll find my settings below.
```
defaults read ~/Library/Preferences/com.apple.HIToolbox.plist
{
    AppleCurrencySymbol =     {
        smRoman = "\\U20ac";
    };
    AppleCurrentKeyboardLayoutInputSourceID = "com.apple.keylayout.German";
    AppleDictationAutoEnable = 0;
    AppleEnabledInputSources =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        },
                {
            "Bundle ID" = "com.apple.PressAndHold";
            InputSourceKind = "Non Keyboard Input Method";
        },
                {
            "Bundle ID" = "com.apple.inputmethod.ironwood";
            InputSourceKind = "Non Keyboard Input Method";
        },
                {
            "Bundle ID" = "com.apple.CharacterPaletteIM";
            InputSourceKind = "Non Keyboard Input Method";
        }
    );
    AppleFnUsageType = 2;
    AppleInputSourceHistory =     (
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        },
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 15000;
            "KeyboardLayout Name" = "USInternational-PC";
        }
    );
    AppleSelectedInputSources =     (
                {
            "Bundle ID" = "com.apple.PressAndHold";
            InputSourceKind = "Non Keyboard Input Method";
        },
                {
            InputSourceKind = "Keyboard Layout";
            "KeyboardLayout ID" = 3;
            "KeyboardLayout Name" = German;
        }
    );
}
```
