### ISSUE TITLE
Fallback to username when name is unavailable in OIDC provider

### ISSUE THREAD

**Issue by tommoor** [outline/outline#4774]
### Discussed in https://github.com/outline/outline/discussions/4766

<div type='discussions-op-text'>

<sup>Originally posted by **OCram85** January 24, 2023</sup>
Just noticed, I can't login to outline after updating to latest version.
When trying to login I got redirected to the landing page again after authetication.

Where there any changes in in OIDC workflow?

Outline log:
```
ERR Error during authentication | error=A name field was not returned in the profile parameter, but is required. stack=UnauthorizedError: A name field was not returned in the profile parameter, but is required.
    at AuthenticationError (/opt/outline/build/server/errors.js:38:34)
    at OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:63:47)
    at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:196:24
    at OAuth2Strategy._passportOauth.Strategy.userProfile (/opt/outline/build/server/routes/auth/providers/oidc.js:32:12)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

OIDC Config:

```
# Gitea Auth
      OIDC_CLIENT_ID: 12345
      OIDC_CLIENT_SECRET: gto_1234
      OIDC_AUTH_URI: https://gitea.foo.com/login/oauth/authorize
      OIDC_TOKEN_URI: https://gitea.foo.com/login/oauth/access_token
      OIDC_USERINFO_URI: https://gitea.foo.com/login/oauth/userinfo

      OIDC_USERNAME_CLAIM: preferred_username
      OIDC_DISPLAY_NAME: OpenID
      OIDC_SCOPES: openid profile email
```

Gitea log:

```
2023/01/24 19:18:51 [63d0210b] router: completed POST /user/two_factor for 89.244.191.73:0, 303 See Other in 5.5ms @ auth/2fa.go:45(auth.TwoFactorPost)
2023/01/24 19:18:51 [63d0210b-2] router: completed GET /login/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Foutline.foo.com%2Fauth%2Foidc.callback&scope=openid%20profile%20email&state=0bbce55828b202b1&client_id=6cc369e4-9127-42ff-9450-1cb24fe4ec6b for 89.244.191.73:0, 303 See Other in 4.8ms @ auth/oauth.go:356(auth.AuthorizeOAuth)
2023/01/24 19:18:51 [63d0210b-3] router: completed POST /login/oauth/access_token for 172.18.0.1:0, 200 OK in 101.7ms @ auth/oauth.go:589(auth.AccessTokenOAuth)
2023/01/24 19:18:52 [63d0210c] router: completed GET /login/oauth/userinfo for 172.18.0.1:0, 200 OK in 6.4ms @ auth/oauth.go:271(auth.InfoOAuth)
2023/01/24 19:18:55 [63d0210f] router: completed GET /login/oauth/authorize?response_type=code&redirect_uri=https%3A%2F%2Foutline.foo.com%2Fauth%2Foidc.callback&scope=openid%20profile%20email&state=7249d463c08c8cab&client_id=6cc369e4-9127-42ff-9450-1cb24fe4ec6b for 89.244.191.73:0, 303 See Other in 5.8ms @ auth/oauth.go:356(auth.AuthorizeOAuth)
2023/01/24 19:18:55 [63d0210f-2] router: completed POST /login/oauth/access_token for 172.18.0.1:0, 200 OK in 101.5ms @ auth/oauth.go:589(auth.AccessTokenOAuth)
2023/01/24 19:18:55 [63d0210f-3] router: completed GET /login/oauth/userinfo for 172.18.0.1:0, 200 OK in 7.2ms @ auth/oauth.go:271(auth.InfoOAuth)
```</div>

**Comment by gkozyrev** [comment]
Same thing with discord, it has "username" instead of "name"

**Comment by majorgear** [comment]
has the fix been merged yet? I'm using the outlinewiki/outline:latest image and still get the error. 

In the meantime, is there a workaround for this issue? I've noticed that container image outlinewiki/outline:0.63.0 doesn't have this issue, so I could go back to that ( new install ).

**Comment by tommoor** [comment]
Fixed in `v0.68.1` yes.

**Comment by majorgear** [comment]
It's still not working.  I have some more apps to migrate to kubernetes today, so I'll revert to 0.63.0 for now and work on this issue more when I have time. So it should work , but something is office.  

For reference, this is with Gitea v1.18.5 and the error is.
```{"error":"A name field was not returned in the profile parameter, but is required.","stack":"UnauthorizedError: A name field was not returned in the profile parameter, but is required.\n at AuthenticationError (/opt/outline/build/server/errors.js:38:34)\n at OAuth2Strategy._verify (/opt/outline/build/server/routes/auth/providers/oidc.js:63:47)\n at /opt/outline/node_modules/passport-oauth2/lib/strategy.js:196:24\n at OAuth2Strategy._passportOauth.Strategy.userProfile (/opt/outline/build/server/routes/auth/providers/oidc.js:32:12)\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (node:internal/process/task_queues:96:5)","level":"error","message":"Error during authentication"}```
