### ISSUE TITLE
Heading links not working

### ISSUE THREAD

**Issue by thumDer** [outline/outline#5403]
For some of our documents we can't use heading links, because it fails to jump to the specified heading on loading, it stays on the top of the page. We cannot find a pattern on what documents are affected. 
Rereshing the page behaves the same.
Clicking in the browsers titlebar and pressing enter will focus on the specified heading though.

Is there any way to debug this?

**Expected behavior**
Consistent behaviour of heading links.

**Screenshots**
![621EAACA-D125-4B98-975F-0D8B8B60AC06](https://github.com/outline/outline/assets/54556708/8367ad9b-e361-448d-9495-7fa9b6b6ab6d)

**Outline (please complete the following information):**
- Install: getoutline.com 

**Desktop (please complete the following information):**
 - OS: Win 11
 - Browser Firefox
 - Version 113.0.2

**Comment by thumDer** [comment]
I've also found that renaming a page also breaks the functionality of heading links, but that seems to be a different issue than this one.

**Comment by tommoor** [comment]
The first issue should be resolved now, I forgot to close this

**Comment by tommoor** [comment]
Still not working quite right, with chromium multiple scroll events in different elements cannot be triggered at the same time so the scrolling sidebar is cancelling out the scrolling content area.

**Comment by thumDer** [comment]
Unfortunately it is still not working for us, still jumps to a completely different location on the document, and hitting enter on the address bar makes it jump to the correct heading. 
The document itself is quite long, the stats are the following:
![kép](https://github.com/outline/outline/assets/54556708/e2ddd36d-5bd3-40f0-9fdf-c19f947a21c4)

**Comment by thumDer** [comment]
@tommoor is it possitble to reopen this issue? We still have the issue for all of our docs, even shorter ones, without images, like his one:
![C2780772-380E-4C1A-AA4A-1BA0DFA84A76](https://github.com/outline/outline/assets/54556708/1b69ec5d-c6fe-4f34-85d5-5358b9e8b135)

**Comment by thumDer** [comment]
Testing it today I've found that heading links are working fine again. Was there any relevant update?

**Comment by tommoor** [comment]
Nothing has been added since the last reopen it the nature of the bug is that it’s sporadic

**Comment by degiooh** [comment]
same here, heading links are not working – or whats the hint?

**Comment by tommoor** [comment]
closed in f214db0ab
