### ISSUE TITLE
Setting text direction for paragraphs instead of the page

### ISSUE THREAD

**Issue by hosimaz** [outline/outline#6836]
The dir="auto" should be set for each paragraphs instead of the entire page.

**To Reproduce**
1. Create a new document
2. Insert RTL text at the first paragraph: "سلام دنیا"
3. Insert LTR text at the second paragraph: "Hello World"
4. See the issue

**Expected behavior**
First paragraph should be RTL
Second paragraph should be LTR
**Screenshots**
![Outline-direction](https://github.com/outline/outline/assets/47596376/f80bfb13-c4cf-47a3-babb-2ad532a3210f)

Expected behavior:
![GoogleDocs-direction](https://github.com/outline/outline/assets/47596376/5db6578e-cc79-421a-8607-9afa79e19f17)

**Comment by behiunforgiven** [comment]
I have the same problem in Outline.

**Comment by talha5389-teraception** [comment]
@tommoor This doesn't work if RTL text is part of a heading

**Comment by tommoor** [comment]
That is the bug that was fixed with https://github.com/outline/outline/commit/6cc0cde1242ea372026b48590ce15a585e4bc9d9

**Comment by talha5389-teraception** [comment]
@tommoor It seems to still happen for me. I am on trial for outline cloud

![image](https://github.com/user-attachments/assets/c0bda74d-091d-47dc-b227-7c599b9e54b7)

This is the content in screenshot. Put non-english text in H1, H2, or H3. It forces whole page to RTL.


```
السلام عليكم
How to acquire?
```

If there is any heading with RTL text, then all headings and table shifts to RTL (paragraphs/non-headings are still in LTR and probably fixed by commit you referenced)

**Comment by tommoor** [comment]
Ah, so it only affects headings – in that case this is just a small remaining bug

**Comment by hosimaz** [comment]
Also using bullet lists and numbering can be confusing because they often follow the direction of the page title's language, not their own.

**Comment by tommoor** [comment]
True, another bug here – I've so far been unable to fix that one, nothing seems to allow the browser to detect list items as RTL
