### ISSUE TITLE
Add support for root path format in Markdown imports

### ISSUE THREAD

**Issue by willzhang** [outline/outline#7512]
**To Reproduce**
1. Go to Settings
2. Click on Import
3. Select Markdown import, and choose `docker.zip` file to import
4. See import success
5. Go back to app, check Collections `docker`, the Imported document images can not be loaded.

![image](https://github.com/user-attachments/assets/80c66244-4067-48f9-8bb3-2f4cc9e52fd6)

I have a large number of documents written locally using the TYPORA editor, each document size 10MB~200MB, with a large number of images in it, and I want to migrate them to the outlines, how should I do it?

Local documents are all standard markdown structures
```
.
├── Document1
│   ├── Chapter1
│   │   ├── assets
│   │   │   ├── image1.png
│   │   │   └── image2.png
│   │   ├── introduction.md
│   │   └── overview.md
│   ├── Chapter2
│   │   ├── images
│   │   │   ├── image3.png
│   │   │   └── image4.png
│   │   ├── details.md
│   │   └── conclusion.md
├── Document2
│   ├── Section1
│   │   ├── assets
│   │   │   ├── pic1.png
│   │   │   └── pic2.png
│   │   ├── summary.md
│   │   └── introduction.md
│   ├── Section2
│   │   ├── images
│   │   │   ├── pic3.png
│   │   │   └── pic4.png
│   │   ├── background.md
│   │   └── results.md

```

**Expected behavior**
Imported document images load success.

**Screenshots**

docker.zip content

![image](https://github.com/user-attachments/assets/08b9978b-175f-441c-b615-2feb4f8c0b66)
![image](https://github.com/user-attachments/assets/7687a388-02a2-40cd-ac54-7e29e577c488)
![image](https://github.com/user-attachments/assets/f30cae1b-ecae-4214-a7ae-8aacd4211ff1)

**Outline (please complete the following information):**
- Install: both getoutline.com and self hosted
- Version: `v0.78.0` and `Outline Setup 1.3.1 - x64.exe`

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version `128.0.6613.113`

**Mobile (please complete the following information):**

**Comment by tommoor** [comment]
Please provide the zip file in question

**Comment by willzhang** [comment]
Here are the test zip file
[docker.zip](https://github.com/user-attachments/files/16838234/docker.zip)

**Comment by tommoor** [comment]
You need to remove the `.` from the file path, so it's just `/uploads/image01.png` and that will resolve the issue, the Markdown importer was designed to import the output of the exporter so it isn't very resilient to little changes like this.

**Comment by willzhang** [comment]
Thanks， it work, but i need to remove the `.` from the file path, Image use `/` root paths are not usually common in markdown，this is a lot of work for document migration for local writing.
![image](https://github.com/user-attachments/assets/4cecab72-7d54-464d-b9f3-ed8dd53a306b)

**Comment by willzhang** [comment]
Ok, i will use this method: Just do a bulk find and replace across your files.

In summary：

This image format is supported
```
![](uploads/image01.png)
![](/uploads/image01.png)
```

This image format is not supported
```
![](./uploads/image01.png)
```

**Comment by whuwangyong** [comment]
> Ok, i will use this method: Just do a bulk find and replace across your files.
> 
> In summary：
> 
> This image format is supported
> 
> ```
> ![](uploads/image01.png)
> ![](/uploads/image01.png)
> ```
> 
> This image format is not supported
> 
> ```
> ![](./uploads/image01.png)
> ```

Hi, @willzhang, I download your docker.zip and modified the image format to `![](uploads/image01.png)`, but after I import the ZIP file into Outline, I got this:

![Image](https://github.com/user-attachments/assets/6fa52c2c-79ec-4a10-b4b2-360d8cf47114)
If I access the `http://mydomain.com/api/attachments.redirect?id=f64bb330-d824-4e88-afc5-0ee8241176ce`, I can get the picture. And I noticed that there is one left parenthesis missing in the URL part of the img format. 

The uploaded files look okay:

![Image](https://github.com/user-attachments/assets/cf3a1fa8-65f6-48cc-9573-5538d9ce9157)


May I ask what might be the cause of this? Thank you for your reply @tommoor .

I use file storage, and the version is 0.82.0.

**Comment by tommoor** [comment]
This was fixed in recent weeks https://github.com/outline/outline/commit/a05c965be2b4812354aef7f13c378ae6faf09e45 and will be in the next release, it affects relative paths specifcially

**Comment by rahmanlathief** [comment]
> > Ok, i will use this method: Just do a bulk find and replace across your files.
> > In summary：
> > This image format is supported
> > ```
> > ![](uploads/image01.png)
> > ![](/uploads/image01.png)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This image format is not supported
> > ```
> > ![](./uploads/image01.png)
> > ```
> 
> Hi, [@willzhang](https://github.com/willzhang), I download your docker.zip and modified the image format to `![](uploads/image01.png)`, but after I import the ZIP file into Outline, I got this:
> 
> ![Image](https://github.com/user-attachments/assets/6fa52c2c-79ec-4a10-b4b2-360d8cf47114) If I access the `http://mydomain.com/api/attachments.redirect?id=f64bb330-d824-4e88-afc5-0ee8241176ce`, I can get the picture. And I noticed that there is one left parenthesis missing in the URL part of the img format.
> 
> The uploaded files look okay:
> 
> ![Image](https://github.com/user-attachments/assets/cf3a1fa8-65f6-48cc-9573-5538d9ce9157)
> 
> May I ask what might be the cause of this? Thank you for your reply [@tommoor](https://github.com/tommoor) .
> 
> I use file storage, and the version is 0.82.0.

hi @whuwangyong have you find the cause / solution? 

im using 0.82.0 as well, check the source code, the fix that mentioned by  @tommoor > a05c965 is there, but yet the problem is still exist

**Comment by rahmanlathief** [comment]
update: solved with upgrading to 0.84.0 😂
