### ISSUE TITLE
Error: User authentication already exists after upgrading to 0.80.0

### ISSUE THREAD

**Issue by kolaente** [outline/outline#7638]
After upgrading to 0.80.0 (now on 0.80.1, still the same issue) it is not possible to log in any more using Authentik.
The logs say

```
{
   "error":"User authentication 80e4bc296aace610f28b32ca61fbd9316bbd009a85b3787cad494137f8b77e39 already exists for d8ed8711-1340-445f-a124-a5f286a77c68, tried to assign to 80ffbb83-5fa5-4df9-86f3-b4f359ff7b4e",
   "level":"error",
   "message":"Error during authentication",
   "stack":"Error: User authentication 80e4bc296aace610f28b32ca61fbd9316bbd009a85b3787cad494137f8b77e39 already exists for d8ed8711-1340-445f-a124-a5f286a77c68, tried to assign to 80ffbb83-5fa5-4df9-86f3-b4f359ff7b4e\n    at userProvisioner (/opt/outline/build/server/commands/userProvisioner.js:56:13)\n    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)\n    at async accountProvisioner (/opt/outline/build/server/commands/accountProvisioner.js:79:12)"
}
```

Nothing changed on the Authentik side, url, email, password etc are all the same. That's different from https://github.com/outline/outline/issues/7271 and https://github.com/outline/outline/issues/7092

**Outline (please complete the following information):**
- Install: self hosted
- Version: 0.80.1 docker tag

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Tried latest chrome and Firefox, no difference

**Comment by kolaente** [comment]
I'm running two instances of outline with an identical setup (same version and Authentik), but only one has this problem.

**Comment by tommoor** [comment]
This is probably indicative of having more than one row in the teams table in the database.

The behaviour here changed in this release in order to tackle other bugs - take a look in the db and remove the duplicate row

**Comment by kolaente** [comment]
Nope, only one team:

```
outline=# select count(*) from teams;
 count
-------
     1
(1 row)

**Comment by Coday-meric** [comment]
Hello,

Same error with same config.
OIDC or SMTP same error.

**Comment by farious-jonrose** [comment]
I resolved this for our organization. Here is what I did:

In `psql`, run the following:

`SELECT * FROM authentication_providers;`

In our case, there were 2 entries in this table, with the same `teamId` column, but different `id` and different `providerID`. I think that this occurred when we were setting up Keycloak/FreeIPA integration and I got our emails wrong in FreeIPA, which passed through the wrong email address to Keycloak and then to Outline.

```
                  id                  | name |   providerId    | enabled |                teamId                |         createdAt          
--------------------------------------+------+-----------------+---------+--------------------------------------+----------------------------
 xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx | oidc | X.com     | t       | zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz | 2024-01-30 04:18:01.088+00
 yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy | oidc | baddomain.X.com | f       | zzzzzzzz-zzzz-zzzz-zzzz-zzzzzzzzzzzz | 2024-01-28 15:50:55.183+00
```
To fix this, run the following:

`UPDATE authentication_providers SET enabled='f' WHERE id='yyyyyyyy-yyyy-yyyy-yyyy-yyyyyyyyyyyy';`

After running this SQL command, we were able to log back into the Outline.

**Comment by patzm** [comment]
thx, I can confirm that this worked for me as well 🙏. @tommoor was there any change in `0.80.0` or `0.80.1` (I am running the latter) that could have triggered that? I think this table was like that before, it had entries dating back to 2022 for me.

**Comment by kolaente** [comment]
> I resolved this for our organization. Here is what I did:
> 
> In `psql`, run the following:
> 
> `SELECT * FROM authentication_providers;`

We have 8 entries in that table. Looks like this is one for each email domain of a user.
We're a non-profit with only volunteers, and everyone uses their personal email address for their account, hence the different email domains.

**Comment by tommoor** [comment]
> We have 8 entries in that table. Looks like this is one for each email domain of a user.

This is the issue that should have been fixed in `v0.80.0`, I'm not sure if we can make it compatible both ways but I'll try.

**Comment by m90** [comment]
> We have 8 entries in that table. Looks like this is one for each email domain of a user.

FWIW we're having a similar issue where we have multiple Providers, but one user somehow mapped to two entries in the `authentication_providers` table. Disabling the incorrect one __and__ deleting the associated `user_authentications` from the database fixed the issue for us.

**Comment by tommoor** [comment]
Should be addressed in 	`v0.80.2` when multiple existing OIDC providers are in the db

**Comment by m90** [comment]
This is still happening for me in 0.80.2. I was temporarily able to resolve the issue by dropping all rows in `user_authentications`, but I already did that before and it seems to have resurfaced. Let me know if I can provide any further details.
