### ISSUE TITLE
Enforce single team when self-hosting

### ISSUE THREAD

**Issue by bmann** [outline/outline#862]
I recently installed Outline on Heroku. I set `DEPLOYMENT=self` and `SUBDOMAINS_ENABLED=false`.

I initially setup Slack authentication, and then setup Google Authentication.

When I logged in with Google Authentication, Outline created a new team for me, linked to my login domain (`mypersonalgoogle.com`). Each user that logs in from a different Google domain (I have three in my `GOOGLE_ALLOWED_DOMAINS`) creates a new team.

My expectation was that with subdomains disabled, I was essentially running Outline in "single team" mode.

A workaround would be explaining how I can invite people to the same Outline team, even if they have a different Google domain. It makes sense to me for a Slack workspace that different Slack == different Outline team, but for Google, I mix and match which accounts I login to, and definitely want to share with users without having them to give them an account on my Google domain.

A feature request would be single team mode, where either no additional teams are created or are only created by an admin.

Thanks for any thoughts on this!

**Comment by tommoor** [comment]
Hi @bmann 

Whilst Outline is an open source product (I wrote [about why this is the case](https://blog.tommoor.com/2019/01/01/you-should-open-source-your-product/) here)  there are really not many special accommodations made in the codebase for self hosting right now.

As the solo maintainer all of my efforts go into the core product experience and the hosted service at http://getoutline.com . I'm not against others taking on these changes however they are unlikely to be priority for myself, hope that makes sense!

**Comment by tommoor** [comment]
> I still see a use case where you have people from multiple Google domains wanting to login to one Outline team (hosted version). Which doesn’t seem possible right now. Can you confirm?

Yes, this seems reasonable. There could be an env flag to force everyone onto the same team.

**Comment by andermurias** [comment]
> Great, thanks for the response! I wanted to share my experience and wonder out loud what made sense.
> 
> I still see a use case where you have people from multiple Google domains wanting to login to one Outline team (hosted version). Which doesn’t seem possible right now. Can you confirm?
> 
> (and feel free to close this issue)

Hi!

I needed something similar, if you don't mind to change a few lines, you can achive if pretty easily.

My case was a bit different but a part of it could work for you, I wanted to allow @gmail users to login in the outline, and also some domains using gsuite to be allowed to login the tool and aloow all of them mto work with the same documents.

My work arround was something like this, 

I've created a variable in `.env`
```
TEAM_ID=teamname
```

And as I wrote in the issue (https://github.com/outline/outline/issues/883#issuecomment-467924911)  I added the next lines in the login with google process. 

They check if the variable exists in the dotenv and if so, uses it as team id for everyone. (the exact part of code is this)

```javascript
let googleId = process.env.TEAM_ID;
  if(!googleId) {
    const googleId = profile.data.hd;
}
```

I'ts not a perfect soultion but could be usefull. Or at least I hope so.

PS: I made this changes since a few months ago and keep updated frequently the outline to the latest version. Didn't have a problem yet :).

**Comment by vikasprogrammer** [comment]
how do I find out the teamname?

**Comment by himanshuagarwal** [comment]
@tommoor Not sure how is this fixed in the new release, Our self-hosted mode still loads up a new separate team if I add any other GOOGLE_ALLOWED_DOMAINS

**Comment by tommoor** [comment]
I wouldn't say it's "fixed", hence the issue still being open but the behavior has gotten better.

I'm a little wary of making this change because the change in behavior might be unwanted for some self-hosting teams that are already running a single wiki for each Google domain and actually liking that setup. So I think we'd need a plan on how to deal with that to close this out.

**Comment by shoan** [comment]
> I wouldn't say it's "fixed", hence the issue still being open but the behavior has gotten better.

Is there a way to allow other google hosted domains to access the same wiki?

**Comment by YoogottamK** [comment]
A temporary workaround:

Instead of
https://github.com/outline/outline/blob/df472ac391257c6f103c5c3a2349cb5f74a0d7b3/server/auth/google.js#L58

We can have
```js
const googleId = process.env.SUBDOMAINS_ENABLED === "true" ? profile.data.hd : profile.data.hd.split(".").slice(-2).join(".");
```


**NOTE**
This will not work if the "domain" itself is a subdomain.

For example,
"domain": `def.ghi.xyz`
"subdomain": `abc.def.ghi.xyz`
