### ISSUE TITLE
Page does not scroll to anchor once document loads

### ISSUE THREAD

**Issue by tommoor** [outline/outline#902]
- Copy a link to a heading
- Paste into new tab
- Page does not scroll to heading

**Comment by teddychan** [comment]
We have the same problem, self hosted, v0.16.3

![image](https://user-images.githubusercontent.com/1013507/53080937-c15a4180-3534-11e9-8ba2-eb1e3168049e.png)

The page cannot scroll to the top, it happens suddenly since yesterday.
We didn't do any upgrade of the outline, and happen for all collections.

**Comment by tommoor** [comment]
Hey Teddy, this is a separate issue - the problem you mention was due to a change in a recent Chrome update and has been fixed on the latest master for several weeks.

Just update and all should be good.

**Comment by teddychan** [comment]
Thanks, @tommoor clarify.
We will ask our team to use another Chrome version.

**Comment by pengzihe** [comment]
Hi, I upgraded to latest version(v0.25.0), but still can't scroll to the top via chrome, the chrome version is 72.0.3626.109.
![image](https://user-images.githubusercontent.com/10286479/53214914-553d2200-3689-11e9-9e77-be187bc50189.png)

**Comment by tommoor** [comment]
Does the behavior of getoutline.com work correctly for you? It's running the latest master.

**Comment by pengzihe** [comment]
HI, I upgraded to release v0.24.0 and It works now. thanks
